USE [DYNAMICS]
GO

/****** Object:  Table [dbo].[GPUserRoundUp]    Script Date: 10/8/2021 11:17:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GPUserRoundUp](
	[ID] [Int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[QueryDate] [Date] NULL,
	[MinUsers] [Int] NULL,
	[AvgUsers] [Int] NULL,
	[MaxUsers] [Int] NULL,
	[MaxID] [Int] NULL,
 CONSTRAINT [PK_GPUserRoundUp] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


