USE [DYNAMICS]
GO

/****** Object:  Trigger [dbo].[LastLoginUpdate]    Script Date: 10/8/2021 11:18:02 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

   
CREATE TRIGGER [dbo].[LastLoginUpdate]     
ON [dbo].[ACTIVITY]  
FOR	INSERT
AS

MERGE dbo.GPLastLogin AS TARGET
USING dbo.ACTIVITY AS SOURCE
ON TARGET.Name = SOURCE.USERID

WHEN MATCHED AND TARGET.LastLogin <> SOURCE.LOGINDAT + SOURCE.LOGINTIM 
THEN UPDATE SET TARGET.LastLogin = SOURCE.LOGINDAT + SOURCE.LOGINTIM

WHEN NOT MATCHED BY TARGET
THEN INSERT (Name, LastLogin) VALUES (SOURCE.USERID, SOURCE.LOGINDAT + SOURCE.LOGINTIM);
GO

ALTER TABLE [dbo].[ACTIVITY] ENABLE TRIGGER [LastLoginUpdate]
GO


